// @vitest-environment jsdom
/**
 * PPTX import snapshot regression tests (#291).
 *
 * Pins the converter output (markdown + import warnings) for every fixture
 * deck in fixtures/pptx/ so layout-inference and converter changes that alter
 * output fail loudly instead of shipping unnoticed — the same deliberate
 * diff-review model as the AI prompt snapshots.
 *
 * The fixtures are synthetic decks (transcribed from real PowerPoint slide
 * XML) covering the known content classes: dominant image + body text, two
 * text columns, decorative icons, verbose bullet machinery, and a manual
 * shape diagram. Real-world decks cannot be committed, so the corpus is
 * generated by `node tools/generate-pptx-fixtures.mjs`.
 *
 * The headless-Chromium conversion path (diagram crops render to PNG) is
 * additionally covered in CI by the `test:pptx-import` script
 * (tools/check-pptx-snapshots.mjs), which diffs the same expectations against
 * the real pptx-import.mjs CLI output. In jsdom the crop path is unavailable,
 * so diagram-heavy slides snapshot their degraded `[Diagram: ...]` markers and
 * warnings — which is exactly the degradation path the post-import report
 * (#290) surfaces.
 *
 * Update deliberately after reviewing an output diff:
 *   UPDATE_PPTX_SNAPSHOTS=1 npx vitest run src/__tests__/pptx-import-snapshots.test.js
 */
import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import markdownit from "markdown-it";
import { PptxExtractor } from "../data/pptx-extractor.js";
import { convertToSlideMd } from "../data/pptx-to-slide-md.js";
import { MarkdownParser } from "../data/markdown-parser.js";

window.markdownit = markdownit;

const FIXTURES_DIR = path.join(import.meta.dirname, "fixtures", "pptx");
const EXPECTED_DIR = path.join(import.meta.dirname, "fixtures", "pptx-expected");
const UPDATE = !!globalThis.process?.env?.UPDATE_PPTX_SNAPSHOTS;

const fixtureNames = fs
  .readdirSync(FIXTURES_DIR)
  .filter((f) => f.toLowerCase().endsWith(".pptx") && !f.startsWith("~$"))
  .sort();

describe("pptx import output snapshots", () => {
  for (const name of fixtureNames) {
    it(`matches the pinned conversion output for ${name}`, async () => {
      const buffer = fs.readFileSync(path.join(FIXTURES_DIR, name));
      const extraction = await PptxExtractor.extract(buffer);
      const markdown = convertToSlideMd(extraction);
      // The markdown must round-trip through the deck parser — a snapshot
      // change that breaks parsing should fail here, not only in the app.
      const deck = new MarkdownParser().parseDeckMarkdown(markdown);
      expect(deck.slides.length).toBe(extraction.slides.length);

      const warnings = (extraction.warnings?.warnings || []).map((w) => ({
        slide: w.slideIndex,
        kind: w.kind,
        message: w.message,
      }));

      const mdPath = path.join(EXPECTED_DIR, `${name}.md`);
      const warningsPath = path.join(EXPECTED_DIR, `${name}.warnings.json`);
      if (UPDATE) {
        fs.mkdirSync(EXPECTED_DIR, { recursive: true });
        fs.writeFileSync(mdPath, markdown);
        fs.writeFileSync(warningsPath, JSON.stringify(warnings, null, 2) + "\n");
        return;
      }

      expect(
        fs.existsSync(mdPath),
        `missing snapshot ${mdPath} — run with UPDATE_PPTX_SNAPSHOTS=1`,
      ).toBe(true);
      const expected = fs.readFileSync(mdPath, "utf8");
      if (markdown !== expected) {
        // findIndex is -1 when markdown is a strict prefix of expected (e.g.
        // a trailing-newline-only change); compare from the end in that case.
        const i = [...markdown].findIndex((ch, j) => ch !== expected[j]);
        const at = i === -1 ? expected.length - 1 : i;
        throw new Error(
          `Conversion output for ${name} changed at char ${at}.\n` +
            `  expected: ...${JSON.stringify(expected.slice(Math.max(0, at - 40), at + 40))}\n` +
            `  actual:   ...${JSON.stringify(markdown.slice(Math.max(0, at - 40), at + 40))}\n` +
            `If this change is intended, update the snapshots:\n` +
            `  UPDATE_PPTX_SNAPSHOTS=1 npx vitest run src/__tests__/pptx-import-snapshots.test.js`,
        );
      }

      const expectedWarnings = JSON.parse(fs.readFileSync(warningsPath, "utf8"));
      expect(warnings, `Import warnings for ${name} changed`).toEqual(expectedWarnings);
    });
  }

  it("has complete snapshot coverage: every fixture pinned, no orphaned expectations", () => {
    expect(fixtureNames.length).toBeGreaterThan(0);
    for (const name of fixtureNames) {
      expect(fs.existsSync(path.join(EXPECTED_DIR, `${name}.md`)), name).toBe(true);
      expect(fs.existsSync(path.join(EXPECTED_DIR, `${name}.warnings.json`)), name).toBe(true);
    }
    // A renamed/deleted fixture must not leave stale expectations behind —
    // they would silently pretend coverage that no longer exists.
    for (const file of fs.readdirSync(EXPECTED_DIR)) {
      if (file === "headless") continue;
      const fixtureName = file.replace(/(\.md|\.warnings\.json)$/, "");
      expect(
        fixtureNames.includes(fixtureName),
        `orphan expectation ${file} (no fixture ${fixtureName})`,
      ).toBe(true);
    }
  });
});
